services:
  con_mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=eL+admLnsVbeCosiT4Sno?1fqU7
    volumes:
      - ./mysql_data:/var/lib/mysql

  con_flaskapp_sqli_error_based:
    build:
      context: ./app
    depends_on:
      - con_mysql
    ports:
      - "5000:5000"
    links:
      - con_mysql

